#[theme] # You have to add this line

#primaryColor = '#000000' # Black

#backgroundColor = '#00325B' # Dark Blue

#secondaryBackgroundColor = '#55B2FF' # Lighter Blue
#textColor = '#FFFFFF' # White

[theme]
# Custom theme colors
primaryColor = "#0B4F6C" # Dark blue
backgroundColor = "#0B4F6C" # Dark blue
secondaryBackgroundColor = "#3D84A8" # Light blue
textColor = "#FFFFFF" # White
